#!/usr/bin/env python3
"""Runs every dart/exNN.dart file, captures its real stdout, derives starter code
and writes src/data/solutions.generated.ts.

Run:  python3 tools/build_solutions.py
"""
import json
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DART_DIR = ROOT / "dart"
OUT_FILE = ROOT / "src" / "data" / "solutions.generated.ts"

DART = shutil.which("dart") or "/Users/apple/development/flutter/bin/dart"

SIG_RE = re.compile(
    r"^(?:void|int|double|String|bool|num|List<[^>]+>|Map<[^>]+>)\s+\w+\s*\(",
)


def signatures(source: str) -> list[str]:
    """Top-level function signatures, flattened to one line each."""
    lines = source.split("\n")
    result: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if SIG_RE.match(line):
            buf = line.rstrip()
            # A signature can span several lines (named parameter blocks).
            while buf.count("(") > buf.count(")") and i + 1 < len(lines):
                i += 1
                buf += " " + lines[i].strip()
            sig = buf.split("=>")[0].split("{", 1)
            head = sig[0] if buf.strip().endswith("{") is False else sig[0]
            head = re.sub(r"\s+", " ", head).strip()
            head = head.rstrip("{").rstrip()
            # Drop a trailing "{" left by block bodies and normalise spacing.
            if head.endswith(")") is False and "(" in head:
                head = head[: head.rfind(")") + 1] if ")" in head else head
            if head:
                result.append(head)
        i += 1
    return result


def preamble(source: str) -> str:
    """Imports plus the `---------- INPUT ----------` constant block."""
    lines = source.split("\n")
    keep: list[str] = []
    for line in lines:
        stripped = line.strip()
        if SIG_RE.match(line):
            break
        keep.append(line)
    # Trim trailing blank lines.
    while keep and keep[-1].strip() == "":
        keep.pop()
    return "\n".join(keep)


def starter_for(source: str, number: int, title: str) -> str:
    sigs = signatures(source)
    sigs = [s for s in sigs if not s.startswith("void main")]
    head = preamble(source)
    parts = [head, ""]
    if sigs:
        parts.append("// Implement these functions:")
        for s in sigs:
            parts.append(f"//   {s}")
        parts.append("")
    parts.append("void main() {")
    parts.append("  // TODO: write your solution here so the output matches the expected output.")
    parts.append("}")
    return "\n".join(parts) + "\n"


def run(path: pathlib.Path) -> tuple[str, str, int]:
    proc = subprocess.run(
        [DART, "run", str(path)],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=str(DART_DIR),
    )
    return proc.stdout, proc.stderr, proc.returncode


def main() -> int:
    files = sorted(DART_DIR.glob("ex*.dart"))
    if not files:
        print("no dart files found", file=sys.stderr)
        return 1

    entries = []
    failures = []
    for path in files:
        number = int(path.stem.replace("ex", ""))
        source = path.read_text()
        first_line = source.split("\n", 1)[0]
        title = first_line.replace("//", "").strip()
        if " - " in title:
            title = title.split(" - ", 1)[1]
        stdout, stderr, code = run(path)
        if code != 0:
            failures.append((path.name, code, stderr[:400]))
            continue
        entries.append(
            {
                "id": number,
                "solution": source,
                "expectedOutput": stdout.rstrip("\n"),
                "starter": starter_for(source, number, title),
            }
        )
        print(f"ok  ex{number:02d}  {len(stdout.splitlines()):4d} lines")

    if failures:
        for name, code, err in failures:
            print(f"FAIL {name} exit={code}\n{err}", file=sys.stderr)
        return 1

    body = ",\n".join(
        "  {}: {{\n    solution: {},\n    expectedOutput: {},\n    starter: {},\n  }}".format(
            e["id"],
            json.dumps(e["solution"]),
            json.dumps(e["expectedOutput"]),
            json.dumps(e["starter"]),
        )
        for e in entries
    )

    ts = (
        "// AUTO-GENERATED by tools/build_solutions.py - do not edit by hand.\n"
        "// Every solution below was executed with the Dart SDK and the expected\n"
        "// output is the real captured stdout.\n\n"
        "export type GeneratedSolution = {\n"
        "  solution: string;\n"
        "  expectedOutput: string;\n"
        "  starter: string;\n"
        "};\n\n"
        "export const solutions: Record<number, GeneratedSolution> = {\n"
        f"{body},\n"
        "};\n"
    )
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(ts)
    print(f"\nwrote {OUT_FILE.relative_to(ROOT)} with {len(entries)} solutions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
